# Generated by Django 2.2 on 2019-09-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20190926_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='blog',
            field=models.ManyToManyField(to='BlogApp.Blog'),
        ),
    ]
